# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecast_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'forecast_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66orecast_streaming.proto\x12\x12\x66orecast_streaming\"N\n\x15\x46orecastStreamRequest\x12\x12\n\nstream_ids\x18\x01 \x03(\t\x12\x0b\n\x03lag\x18\x02 \x01(\x05\x12\x14\n\x0creturn_every\x18\x03 \x01(\x05\"D\n\nEdgeResult\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x16\n\x0e\x63lassification\x18\x03 \x01(\x05\"A\n\x0e\x45\x64geResultList\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.forecast_streaming.EdgeResult\"\xf4\x01\n\x14\x46orecastStreamUpdate\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12O\n\x0c\x65\x64ge_results\x18\x03 \x03(\x0b\x32\x39.forecast_streaming.ForecastStreamUpdate.EdgeResultsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x1aV\n\x10\x45\x64geResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".forecast_streaming.EdgeResultList:\x02\x38\x01\x32\x80\x01\n\x15\x46orecastStreamService\x12g\n\x0eStreamForecast\x12).forecast_streaming.ForecastStreamRequest\x1a(.forecast_streaming.ForecastStreamUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecast_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTSTREAMUPDATE_EDGERESULTSENTRY']._loaded_options = None
  _globals['_FORECASTSTREAMUPDATE_EDGERESULTSENTRY']._serialized_options = b'8\001'
  _globals['_FORECASTSTREAMREQUEST']._serialized_start=48
  _globals['_FORECASTSTREAMREQUEST']._serialized_end=126
  _globals['_EDGERESULT']._serialized_start=128
  _globals['_EDGERESULT']._serialized_end=196
  _globals['_EDGERESULTLIST']._serialized_start=198
  _globals['_EDGERESULTLIST']._serialized_end=263
  _globals['_FORECASTSTREAMUPDATE']._serialized_start=266
  _globals['_FORECASTSTREAMUPDATE']._serialized_end=510
  _globals['_FORECASTSTREAMUPDATE_EDGERESULTSENTRY']._serialized_start=424
  _globals['_FORECASTSTREAMUPDATE_EDGERESULTSENTRY']._serialized_end=510
  _globals['_FORECASTSTREAMSERVICE']._serialized_start=513
  _globals['_FORECASTSTREAMSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
