# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'forecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66orecast.proto\x12\tinference\";\n\x10InferenceRequest\x12\x12\n\nstream_ids\x18\x01 \x03(\t\x12\x13\n\x0bnum_records\x18\x02 \x01(\x05\"D\n\nEdgeResult\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x16\n\x0e\x63lassification\x18\x03 \x01(\x05\"8\n\x0e\x45\x64geResultList\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.inference.EdgeResult\"\xdc\x01\n\x11InferenceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x43\n\x0c\x65\x64ge_results\x18\x03 \x03(\x0b\x32-.inference.InferenceResponse.EdgeResultsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x1aM\n\x10\x45\x64geResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.inference.EdgeResultList:\x02\x38\x01\x32T\n\x10InferenceService\x12@\n\x03Run\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCERESPONSE_EDGERESULTSENTRY']._loaded_options = None
  _globals['_INFERENCERESPONSE_EDGERESULTSENTRY']._serialized_options = b'8\001'
  _globals['_INFERENCEREQUEST']._serialized_start=29
  _globals['_INFERENCEREQUEST']._serialized_end=88
  _globals['_EDGERESULT']._serialized_start=90
  _globals['_EDGERESULT']._serialized_end=158
  _globals['_EDGERESULTLIST']._serialized_start=160
  _globals['_EDGERESULTLIST']._serialized_end=216
  _globals['_INFERENCERESPONSE']._serialized_start=219
  _globals['_INFERENCERESPONSE']._serialized_end=439
  _globals['_INFERENCERESPONSE_EDGERESULTSENTRY']._serialized_start=362
  _globals['_INFERENCERESPONSE_EDGERESULTSENTRY']._serialized_end=439
  _globals['_INFERENCESERVICE']._serialized_start=441
  _globals['_INFERENCESERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
